# Generated by Django 6.0.2 on 2026-03-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='amount',
            new_name='quantity',
        ),
    ]
